const express = require("express")
const authController = require("../controllers/auth")
const accountController = require("../controllers/account")
const userController = require("../controllers/user")
const groupController = require("../controllers/group")
const chatController = require("../controllers/chat")
const gameController = require("../controllers/game")
const searchController = require("../controllers/search")
const router = express.Router()

module.exports = (app, db) => {
  router.get('/', function (req, res) {
    res.render('index')
  })

  router.post('/register', userController.register)
  router.post('/group/create', groupController.create)
  router.post('/account', accountController.update)
  router.post('/account/create', accountController.create)
  router.post('/account/login', accountController.login)
  router.post('/account/validate_code', accountController.validate_code)
  router.post('/account/validate/:code', accountController.validate)
  router.post('/account/data', authController, accountController.data)
  router.get('/account/notifications', authController,accountController.getNotifications)
  router.get('/account/notifications/count', authController,accountController.getNotificationsCount)
  router.get('/account/:id', authController,accountController.getById)
  router.post('/group/update', groupController.update)
  router.post('/game/create', gameController.create)
  router.post('/game/save', gameController.save)
  router.post('/game', gameController.get)
  router.post('/group', groupController.get)
  router.post('/chat', chatController.get)
  router.post('/playlist', gameController.playlist)
  router.post('/gamecount', gameController.count)
  router.post('/eco/search', gameController.ecoSearch)
  router.post('/eco/search/pgn', gameController.ecoSearchPgn)
  router.post('/eco/pgn', gameController.searchPgn)
  router.post('/eco/pgn/random', gameController.randomPgn)
  router.post('/group/random', groupController.random)
  router.post('/search', searchController.search)
  router.post('/dash/search', searchController.dash)
  router.post('/online', searchController.online)
  router.post('/groups', searchController.groups)

	return app.use('/', router)
}